CC     = g++ -O2
CFLAGS =

all:
	${CC} ${CFLAGS} ukqcd2mdp.cpp -o ukqcd2mdp.exe
	${CC} ${CFLAGS} milc2mdp.cpp -o milc2mdp.exe
	${CC} ${CFLAGS} asciimilc2mdp.cpp -o asciimilc2mdp.exe
	${CC} ${CFLAGS} duncan2mdp.cpp -o duncan2mdp.exe
	${CC} ${CFLAGS} luigi2mdp.cpp -o luigi2mdp.exe
